/**
 * RPC v2 的同源 JSON Schema 定义。
 *
 * 这里的对象就是协议权威源：运行时 conformance 使用它，发布文件
 * `rpc-v2.schema.json` 由脚本从此对象生成。新增方法或事件时必须同时
 * 更新方法目录，避免能力、路由和 Schema 各自漂移。
 */
import { RPC_V2_METHODS } from "./methods";

export type JsonSchemaPrimitive = string | number | boolean | null;
export type JsonSchemaValue = JsonSchemaPrimitive | JsonSchemaValue[] | { [key: string]: JsonSchemaValue };
export type JsonSchema = { [key: string]: JsonSchemaValue };

const stringSchema: JsonSchema = { type: "string" };
const objectSchema: JsonSchema = { type: "object", additionalProperties: true };

const sessionEventTypes = [
	"session.opened",
	"session.closed",
	"session.deleted",
	"session.title.changed",
	"session.recovery.available",
	"session.recovered",
	"session.corrupt",
	"run.accepted",
	"run.started",
	"run.state.changed",
	"run.completed",
	"run.failed",
	"run.aborted",
	"run.interrupted",
	"turn.started",
	"turn.completed",
	"message.started",
	"message.delta",
	"message.completed",
	"tool.queued",
	"tool.started",
	"tool.progress",
	"tool.completed",
	"tool.cancelled",
	"queue.item.added",
	"queue.item.cancelled",
	"queue.item.promoted",
	"queue.settings.changed",
	"approval.requested",
	"approval.resolved",
	"approval.expired",
	"approval.cancelled",
	"approval.rule.changed",
	"interaction.requested",
	"interaction.answered",
	"interaction.cancelled",
	"interaction.expired",
	"todo.changed",
	"todo.reminder",
	"goal.changed",
	"planMode.changed",
	"subagent.started",
	"subagent.progress",
	"subagent.completed",
	"subagent.failed",
	"subagent.aborted",
	"subagent.event",
	"context.usage.changed",
	"context.health.changed",
	"context.maintenance.started",
	"context.maintenance.completed",
	"context.checkpoint.created",
	"context.digest.created",
	"retry.started",
	"retry.cancelled",
	"retry.completed",
	"retry.fallback.applied",
	"retry.fallback.succeeded",
	"integration.changed",
	"integration.health.changed",
	"auth.login.state.changed",
	"evidence.recorded",
	"session.notice",
	"worktree.created",
	"worktree.state.changed",
	"worktree.setup.started",
	"worktree.setup.completed",
	"worktree.apply.started",
	"worktree.apply.completed",
	"worktree.apply.conflicted",
	"worktree.archived",
] as const;

const errorReasons = [
	"PARSE_ERROR",
	"INVALID_REQUEST",
	"METHOD_NOT_FOUND",
	"INVALID_PARAMS",
	"INTERNAL_ERROR",
	"NOT_INITIALIZED",
	"VERSION_INCOMPATIBLE",
	"CAPABILITY_UNAVAILABLE",
	"SESSION_NOT_FOUND",
	"SESSION_LOCKED",
	"SESSION_STATE_CONFLICT",
	"SESSION_CORRUPT",
	"RUN_NOT_FOUND",
	"RUN_STATE_CONFLICT",
	"QUEUE_ITEM_NOT_FOUND",
	"APPROVAL_NOT_PENDING",
	"APPROVAL_SCOPE_NOT_ALLOWED",
	"PROVIDER_AUTH_REQUIRED",
	"MODEL_UNAVAILABLE",
	"RATE_LIMITED",
	"HOST_CAPABILITY_UNAVAILABLE",
	"HOST_TOOL_FAILED",
	"RESOURCE_NOT_FOUND",
	"RESOURCE_INVALID",
	"INTEGRATION_UNAVAILABLE",
	"PAYLOAD_TOO_LARGE",
	"IDEMPOTENCY_CONFLICT",
] as const;

const paramsByMethod: Record<string, JsonSchema> = {
	initialize: {
		type: "object",
		properties: {
			protocolVersion: stringSchema,
			client: {
				type: "object",
				properties: { name: stringSchema, version: stringSchema },
				required: ["name", "version"],
				additionalProperties: true,
			},
			locale: stringSchema,
			host: objectSchema,
			capabilities: objectSchema,
		},
		required: ["protocolVersion", "client"],
		additionalProperties: true,
	},
	"server.getCapabilities": {
		type: "object",
		properties: { knownRevision: { type: "integer", minimum: 0 } },
		additionalProperties: false,
	},
	"server.getHealth": { type: "object", additionalProperties: false },
	"server.getDiagnostics": {
		type: "object",
		properties: {
			detail: { enum: ["summary", "full"] },
			redaction: { const: "strict" },
			includeSession: stringSchema,
		},
		additionalProperties: false,
	},
	"server.shutdown": {
		type: "object",
		properties: { mode: { enum: ["graceful", "force"] }, timeoutMs: { type: "integer", minimum: 0 } },
		additionalProperties: false,
	},
	"stream.configure": {
		type: "object",
		properties: {
			thinkingDeltas: { type: "boolean" },
			subagents: { enum: ["off", "progress", "events"] },
			maxTransientEventsPerSecond: { type: "integer", minimum: 1 },
		},
		additionalProperties: false,
	},
	"session.list": {
		type: "object",
		properties: {
			query: stringSchema,
			cwd: stringSchema,
			statuses: { type: "array", items: stringSchema },
			sort: { enum: ["updated_desc", "updated_asc", "created_desc", "created_asc"] },
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		additionalProperties: false,
	},
	"session.get": {
		type: "object",
		properties: { sessionId: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"session.create": {
		type: "object",
		properties: {
			cwd: stringSchema,
			title: stringSchema,
			parentSessionId: stringSchema,
			executionProfileId: stringSchema,
			meta: objectSchema,
		},
		required: ["cwd", "meta"],
		additionalProperties: false,
	},
	"session.open": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			access: { enum: ["read_write", "read_only"] },
			stealExpiredLease: { type: "boolean" },
			meta: objectSchema,
		},
		required: ["sessionId", "meta"],
		additionalProperties: false,
	},
	"session.sync": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			afterSequence: { type: ["integer", "null"], minimum: 0 },
			stream: objectSchema,
		},
		required: ["sessionId", "leaseId"],
		additionalProperties: false,
	},
	"session.unsync": {
		type: "object",
		properties: { subscriptionId: stringSchema },
		required: ["subscriptionId"],
		additionalProperties: false,
	},
	"session.events.list": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			afterSequence: { type: "integer", minimum: 0 },
			beforeSequence: { type: "integer", minimum: 0 },
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
			types: { type: "array", items: stringSchema },
		},
		required: ["sessionId"],
		additionalProperties: false,
	},
	"session.messages.list": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		required: ["sessionId"],
		additionalProperties: false,
	},
	"session.rename": {
		type: "object",
		properties: { sessionId: stringSchema, leaseId: stringSchema, name: stringSchema, meta: objectSchema },
		required: ["sessionId", "leaseId", "name", "meta"],
		additionalProperties: false,
	},
	"session.branch": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			entryId: stringSchema,
			title: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "entryId", "meta"],
		additionalProperties: false,
	},
	"session.handoff": {
		type: "object",
		properties: { sessionId: stringSchema, leaseId: stringSchema, instructions: stringSchema, meta: objectSchema },
		required: ["sessionId", "leaseId", "meta"],
		additionalProperties: false,
	},
	"session.export": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			format: { enum: ["html", "jsonl"] },
			destination: { enum: ["artifact", "hostPath"] },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "format", "destination", "meta"],
		additionalProperties: false,
	},
	"session.stats": {
		type: "object",
		properties: { sessionId: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"usage.stats": {
		type: "object",
		properties: {
			days: { type: "integer", minimum: 1, maximum: 90 },
			sessionLimit: { type: "integer", minimum: 1, maximum: 500 },
		},
		additionalProperties: false,
	},
	"session.recover": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			strategy: { enum: ["continue", "mark_aborted", "read_only"] },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "strategy", "meta"],
		additionalProperties: false,
	},
	"session.delete": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			mode: { enum: ["trash", "permanent"] },
			expectedRevision: { type: "integer", minimum: 0 },
			meta: objectSchema,
		},
		required: ["sessionId", "meta"],
		additionalProperties: false,
	},
	"session.close": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			runningBehavior: { enum: ["reject", "abort"] },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "meta"],
		additionalProperties: false,
	},
	"run.start": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			content: { type: "array", items: objectSchema },
			model: objectSchema,
			thinking: stringSchema,
			goal: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "content", "meta"],
		additionalProperties: false,
	},
	"run.steer": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			runId: stringSchema,
			content: { type: "array", items: objectSchema },
			delivery: { enum: ["immediate", "next_safe_point"] },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "runId", "content", "delivery", "meta"],
		additionalProperties: false,
	},
	"run.followUp": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			content: { type: "array", items: objectSchema },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "content", "meta"],
		additionalProperties: false,
	},
	"run.replace": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			expectedRunId: stringSchema,
			content: { type: "array", items: objectSchema },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "expectedRunId", "content", "meta"],
		additionalProperties: false,
	},
	"run.abort": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			runId: stringSchema,
			reason: { enum: ["user", "close", "shutdown"] },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "runId", "reason", "meta"],
		additionalProperties: false,
	},
	"retry.cancel": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			runId: stringSchema,
			retryId: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "runId", "meta"],
		additionalProperties: false,
	},
	"queue.list": {
		type: "object",
		properties: { sessionId: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"queue.cancel": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			queueItemId: stringSchema,
			expectedStatus: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "queueItemId", "meta"],
		additionalProperties: false,
	},
	"settings.get": {
		type: "object",
		properties: { scope: { enum: ["session", "workspace", "global"] }, sessionId: stringSchema, cwd: stringSchema },
		required: ["scope"],
		additionalProperties: false,
	},
	"settings.update": {
		type: "object",
		properties: {
			scope: { enum: ["session", "workspace", "global"] },
			sessionId: stringSchema,
			leaseId: stringSchema,
			cwd: stringSchema,
			patch: objectSchema,
			meta: objectSchema,
		},
		required: ["scope", "patch", "meta"],
		additionalProperties: false,
	},
	"model.list": {
		type: "object",
		properties: { provider: stringSchema, includeUnavailable: { type: "boolean" } },
		additionalProperties: false,
	},
	"model.select": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			provider: stringSchema,
			modelId: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "provider", "modelId", "meta"],
		additionalProperties: false,
	},
	"thinking.set": {
		type: "object",
		properties: { sessionId: stringSchema, leaseId: stringSchema, level: stringSchema, meta: objectSchema },
		required: ["sessionId", "leaseId", "level", "meta"],
		additionalProperties: false,
	},
	"execution.profile.list": {
		type: "object",
		properties: { includeUnavailable: { type: "boolean" } },
		additionalProperties: false,
	},
	"auth.provider.list": { type: "object", additionalProperties: false },
	"auth.login.start": {
		type: "object",
		properties: { providerId: stringSchema, meta: objectSchema },
		required: ["providerId", "meta"],
		additionalProperties: false,
	},
	"auth.login.cancel": {
		type: "object",
		properties: { loginId: stringSchema, meta: objectSchema },
		required: ["loginId", "meta"],
		additionalProperties: false,
	},
	"provider.config.create": {
		type: "object",
		properties: {
			providerId: stringSchema,
			baseUrl: stringSchema,
			api: {
				enum: [
					"openai-completions",
					"openai-responses",
					"openai-codex-responses",
					"azure-openai-responses",
					"anthropic-messages",
					"google-generative-ai",
					"google-gemini-cli",
					"google-vertex",
				],
			},
			auth: { enum: ["apiKey", "none"] },
			discovery: {
				type: "object",
				properties: {
					type: { enum: ["openai-models-list", "proxy", "litellm", "ollama", "llama.cpp", "lm-studio"] },
				},
				required: ["type"],
				additionalProperties: false,
			},
			apiKey: stringSchema,
			meta: objectSchema,
		},
		required: ["providerId", "baseUrl", "auth", "meta"],
		additionalProperties: false,
	},
	"provider.model.add": {
		type: "object",
		properties: {
			providerId: stringSchema,
			modelId: stringSchema,
			displayName: stringSchema,
			api: {
				enum: [
					"openai-completions",
					"openai-responses",
					"openai-codex-responses",
					"azure-openai-responses",
					"anthropic-messages",
					"google-generative-ai",
					"google-gemini-cli",
					"google-vertex",
				],
			},
			contextWindow: { type: "integer", minimum: 1 },
			maxTokens: { type: "integer", minimum: 1 },
			reasoning: { type: "boolean" },
			supportsImage: { type: "boolean" },
			supportsTools: { type: "boolean" },
			meta: objectSchema,
		},
		required: ["providerId", "modelId", "meta"],
		additionalProperties: false,
	},
	"command.list": {
		type: "object",
		properties: { sessionId: stringSchema, knownRevision: { type: "integer", minimum: 0 } },
		additionalProperties: false,
	},
	"todo.set": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			phases: { type: "array", items: objectSchema },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "phases", "meta"],
		additionalProperties: false,
	},
	"integration.list": {
		type: "object",
		properties: {
			kinds: { type: "array", items: stringSchema },
			statuses: { type: "array", items: stringSchema },
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		additionalProperties: false,
	},
	"integration.get": {
		type: "object",
		properties: { integrationId: stringSchema },
		required: ["integrationId"],
		additionalProperties: false,
	},
	"integration.setEnabled": {
		type: "object",
		properties: {
			integrationId: stringSchema,
			enabled: { type: "boolean" },
			expectedRevision: { type: "integer", minimum: 0 },
			meta: objectSchema,
		},
		required: ["integrationId", "enabled", "meta"],
		additionalProperties: false,
	},
	"integration.refresh": {
		type: "object",
		properties: { integrationId: stringSchema, meta: objectSchema },
		required: ["meta"],
		additionalProperties: false,
	},
	"approval.list": {
		type: "object",
		properties: { sessionId: stringSchema, status: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"approval.decide": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			approvalId: stringSchema,
			decision: { enum: ["allow", "deny"] },
			scope: { enum: ["once", "session", "workspace", "global"] },
			persistRule: { type: "boolean" },
			comment: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "approvalId", "decision", "scope", "persistRule", "meta"],
		additionalProperties: false,
	},
	"approval.rules.list": {
		type: "object",
		properties: {
			scope: { enum: ["session", "workspace", "global"] },
			sessionId: stringSchema,
			cwd: stringSchema,
			includeInherited: { type: "boolean" },
		},
		additionalProperties: false,
	},
	"approval.rules.revoke": {
		type: "object",
		properties: {
			scope: stringSchema,
			sessionId: stringSchema,
			cwd: stringSchema,
			ruleId: stringSchema,
			expectedRevision: { type: "integer", minimum: 0 },
			meta: objectSchema,
		},
		required: ["ruleId", "meta"],
		additionalProperties: false,
	},
	"approval.policy.get": {
		type: "object",
		properties: { scope: stringSchema, sessionId: stringSchema, cwd: stringSchema },
		additionalProperties: false,
	},
	"approval.policy.update": {
		type: "object",
		properties: {
			scope: stringSchema,
			sessionId: stringSchema,
			cwd: stringSchema,
			patch: objectSchema,
			expectedRevision: { type: "integer", minimum: 0 },
			meta: objectSchema,
		},
		required: ["scope", "patch", "meta"],
		additionalProperties: false,
	},
	"interaction.list": {
		type: "object",
		properties: { sessionId: stringSchema, status: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"interaction.respond": {
		anyOf: [
			{
				type: "object",
				properties: {
					sessionId: stringSchema,
					leaseId: stringSchema,
					interactionId: stringSchema,
					response: objectSchema,
					meta: objectSchema,
				},
				required: ["sessionId", "leaseId", "interactionId", "response", "meta"],
				additionalProperties: false,
			},
			{
				type: "object",
				properties: { interactionId: stringSchema, response: objectSchema, meta: objectSchema },
				required: ["interactionId", "response", "meta"],
				additionalProperties: false,
			},
		],
	},
	"interaction.cancel": {
		anyOf: [
			{
				type: "object",
				properties: {
					sessionId: stringSchema,
					leaseId: stringSchema,
					interactionId: stringSchema,
					reason: stringSchema,
					meta: objectSchema,
				},
				required: ["sessionId", "leaseId", "interactionId", "meta"],
				additionalProperties: false,
			},
			{
				type: "object",
				properties: { interactionId: stringSchema, reason: stringSchema, meta: objectSchema },
				required: ["interactionId", "meta"],
				additionalProperties: false,
			},
		],
	},
	"subagent.list": {
		type: "object",
		properties: { sessionId: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"subagent.messages.list": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			subagentId: stringSchema,
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		required: ["sessionId", "subagentId"],
		additionalProperties: false,
	},
	"subagent.send": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			subagentId: stringSchema,
			message: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "subagentId", "message", "meta"],
		additionalProperties: false,
	},
	"subagent.abort": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			subagentId: stringSchema,
			reason: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "subagentId", "meta"],
		additionalProperties: false,
	},
	"context.get": {
		type: "object",
		properties: { sessionId: stringSchema },
		required: ["sessionId"],
		additionalProperties: false,
	},
	"context.digests.list": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		required: ["sessionId"],
		additionalProperties: false,
	},
	"context.checkpoints.list": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		required: ["sessionId"],
		additionalProperties: false,
	},
	"context.compact": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			instructions: stringSchema,
			strategy: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "meta"],
		additionalProperties: false,
	},
	"context.maintenance.cancel": {
		type: "object",
		properties: { sessionId: stringSchema, leaseId: stringSchema, maintenanceId: stringSchema, meta: objectSchema },
		required: ["sessionId", "leaseId", "maintenanceId", "meta"],
		additionalProperties: false,
	},
	"evidence.list": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			runId: stringSchema,
			kinds: { type: "array", items: stringSchema },
			verdicts: { type: "array", items: stringSchema },
			cursor: stringSchema,
			limit: { type: "integer", minimum: 1, maximum: 100 },
		},
		required: ["sessionId"],
		additionalProperties: false,
	},
	"evidence.get": {
		type: "object",
		properties: { sessionId: stringSchema, evidenceId: stringSchema },
		required: ["sessionId", "evidenceId"],
		additionalProperties: false,
	},
	"artifact.read": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			artifactId: stringSchema,
			offset: { type: "integer", minimum: 0 },
			limit: { type: "integer", minimum: 1 },
		},
		required: ["sessionId", "artifactId", "offset", "limit"],
		additionalProperties: false,
	},
	"resource.upload.begin": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			mediaType: stringSchema,
			fileName: stringSchema,
			byteLength: { type: "integer", minimum: 0 },
			sha256: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "mediaType", "byteLength", "sha256", "meta"],
		additionalProperties: false,
	},
	"resource.upload.chunk": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			uploadId: stringSchema,
			offset: { type: "integer", minimum: 0 },
			dataBase64: stringSchema,
			chunkSha256: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "uploadId", "offset", "dataBase64", "chunkSha256", "meta"],
		additionalProperties: false,
	},
	"resource.upload.commit": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			uploadId: stringSchema,
			sha256: stringSchema,
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "uploadId", "sha256", "meta"],
		additionalProperties: false,
	},
	"resource.registerHostUri": {
		type: "object",
		properties: {
			sessionId: stringSchema,
			leaseId: stringSchema,
			uri: stringSchema,
			metadata: objectSchema,
			access: { enum: ["read", "read_write"] },
			meta: objectSchema,
		},
		required: ["sessionId", "leaseId", "uri", "meta"],
		additionalProperties: false,
	},
	"resource.release": {
		type: "object",
		properties: { sessionId: stringSchema, leaseId: stringSchema, resourceId: stringSchema, meta: objectSchema },
		required: ["sessionId", "leaseId", "resourceId", "meta"],
		additionalProperties: false,
	},
	"host.capabilities.update": {
		type: "object",
		properties: {
			revision: { type: "integer", minimum: 0 },
			tools: { type: "array", items: objectSchema },
			uriSchemes: { type: "array", items: objectSchema },
		},
		additionalProperties: false,
	},
	"worktree.create": {
		type: "object",
		properties: {
			projectCwd: stringSchema,
			repoId: stringSchema,
			base: {
				type: "object",
				properties: {
					kind: { enum: ["branch", "commit"] },
					value: stringSchema,
					resolvedOid: stringSchema,
				},
				required: ["kind", "value", "resolvedOid"],
				additionalProperties: false,
			},
			branchName: stringSchema,
			purpose: { const: "session" },
			setupActionId: stringSchema,
			meta: {
				type: "object",
				properties: { idempotencyKey: stringSchema },
				required: ["idempotencyKey"],
				additionalProperties: false,
			},
		},
		required: ["projectCwd", "repoId", "base", "purpose", "meta"],
		additionalProperties: false,
	},
	"worktree.get": {
		type: "object",
		properties: { worktreeId: stringSchema },
		required: ["worktreeId"],
		additionalProperties: false,
	},
	"worktree.list": {
		type: "object",
		properties: {
			state: {
				anyOf: [
					{
						enum: [
							"creating",
							"setup_pending",
							"ready",
							"in_use",
							"dirty",
							"applying",
							"conflicted",
							"archiving",
							"archived",
							"failed",
						],
					},
					{
						type: "array",
						items: {
							enum: [
								"creating",
								"setup_pending",
								"ready",
								"in_use",
								"dirty",
								"applying",
								"conflicted",
								"archiving",
								"archived",
								"failed",
							],
						},
					},
				],
			},
			states: {
				type: "array",
				items: {
					enum: [
						"creating",
						"setup_pending",
						"ready",
						"in_use",
						"dirty",
						"applying",
						"conflicted",
						"archiving",
						"archived",
						"failed",
					],
				},
			},
			repoId: stringSchema,
			environmentId: stringSchema,
		},
		additionalProperties: false,
	},
	"worktree.setup.start": {
		type: "object",
		properties: {
			worktreeId: stringSchema,
			setupActionId: stringSchema,
			meta: {
				type: "object",
				properties: { idempotencyKey: stringSchema },
				required: ["idempotencyKey"],
				additionalProperties: false,
			},
		},
		required: ["worktreeId", "meta"],
		additionalProperties: false,
	},
	"worktree.setup.cancel": {
		type: "object",
		properties: {
			worktreeId: stringSchema,
			meta: {
				type: "object",
				properties: { idempotencyKey: stringSchema },
				required: ["idempotencyKey"],
				additionalProperties: false,
			},
		},
		required: ["worktreeId", "meta"],
		additionalProperties: false,
	},
	"worktree.apply.prepare": {
		type: "object",
		properties: {
			worktreeId: stringSchema,
			expectedWorktreeRevision: { type: "integer", minimum: 0 },
			expectedTargetSnapshotId: stringSchema,
			strategy: { enum: ["patch", "merge_commit"] },
			meta: {
				type: "object",
				properties: { idempotencyKey: stringSchema },
				required: ["idempotencyKey"],
				additionalProperties: false,
			},
		},
		required: ["worktreeId", "expectedWorktreeRevision", "expectedTargetSnapshotId", "strategy", "meta"],
		additionalProperties: false,
	},
	"worktree.apply": {
		type: "object",
		properties: {
			planId: stringSchema,
			expectedWorktreeRevision: { type: "integer", minimum: 0 },
			expectedTargetSnapshotId: stringSchema,
			meta: {
				type: "object",
				properties: { idempotencyKey: stringSchema },
				required: ["idempotencyKey"],
				additionalProperties: false,
			},
		},
		required: ["planId", "expectedWorktreeRevision", "expectedTargetSnapshotId", "meta"],
		additionalProperties: false,
	},
	"worktree.archive": {
		type: "object",
		properties: {
			worktreeId: stringSchema,
			expectedRevision: { type: "integer", minimum: 0 },
			retainChanges: { type: "boolean" },
			meta: {
				type: "object",
				properties: { idempotencyKey: stringSchema },
				required: ["idempotencyKey"],
				additionalProperties: false,
			},
		},
		required: ["worktreeId", "expectedRevision", "meta"],
		additionalProperties: false,
	},
};

export const RPC_V2_SCHEMA: JsonSchema = {
	$schema: "https://json-schema.org/draft/2020-12/schema",
	$id: "https://san.dev/protocol/rpc-v2.schema.json",
	title: "San RPC v2",
	version: "2.0",
	type: "object",
	additionalProperties: false,
	properties: {
		jsonrpc: { const: "2.0" },
		id: { type: ["string", "null"] },
		method: stringSchema,
		params: objectSchema,
		result: objectSchema,
		error: {
			type: "object",
			properties: {
				code: { type: "integer" },
				message: stringSchema,
				data: {
					type: "object",
					properties: {
						reason: { enum: [...errorReasons] },
						category: {
							enum: ["protocol", "validation", "auth", "conflict", "not_found", "rate_limit", "io", "internal"],
						},
						retryable: { type: "boolean" },
						correlationId: stringSchema,
					},
					required: ["reason", "category", "retryable", "correlationId"],
					additionalProperties: true,
				},
			},
			required: ["code", "message"],
			additionalProperties: false,
		},
	},
	allOf: [
		// biome-ignore lint/complexity/useLiteralKeys lint/suspicious/noThenProperty: JSON Schema 规范要求使用 then 关键字。
		{ if: { required: ["method"] }, ["then"]: { required: ["jsonrpc", "method", "params"] } },
		// biome-ignore lint/complexity/useLiteralKeys lint/suspicious/noThenProperty: JSON Schema 规范要求使用 then 关键字。
		{ if: { required: ["result"] }, ["then"]: { required: ["jsonrpc", "id", "result"] } },
		// biome-ignore lint/complexity/useLiteralKeys lint/suspicious/noThenProperty: JSON Schema 规范要求使用 then 关键字。
		{ if: { required: ["error"] }, ["then"]: { required: ["jsonrpc", "id", "error"] } },
	],
	definitions: {
		methods: {
			type: "object",
			properties: Object.fromEntries(RPC_V2_METHODS.map(name => [name, paramsByMethod[name] ?? objectSchema])),
			additionalProperties: false,
		},
		sessionEvent: {
			type: "object",
			properties: {
				schemaVersion: { const: 1 },
				eventId: stringSchema,
				sessionId: stringSchema,
				sequence: { type: "integer", minimum: 1 },
				timestamp: { type: "string", format: "date-time" },
				runId: stringSchema,
				turnId: stringSchema,
				type: { enum: [...sessionEventTypes] },
				durability: { enum: ["durable", "transient"] },
				data: {},
			},
			required: ["schemaVersion", "eventId", "sessionId", "sequence", "timestamp", "type", "durability", "data"],
			additionalProperties: false,
		},
		capability: {
			type: "object",
			properties: {
				version: { type: "integer", minimum: 1 },
				status: { enum: ["available", "degraded", "unavailable"] },
				reasonCode: stringSchema,
				message: stringSchema,
				details: objectSchema,
			},
			required: ["version", "status"],
			additionalProperties: false,
		},
	},
	meta: { methods: [...RPC_V2_METHODS], eventTypes: [...sessionEventTypes] },
};

export function paramsSchemaForMethod(method: string): JsonSchema | undefined {
	return paramsByMethod[method];
}

export function isKnownRpcV2Method(method: string): boolean {
	return RPC_V2_METHODS.includes(method);
}
