/**
 * Context Steady State types.
 */

export const CONTEXT_STEADY_ACTIVATION_SCHEMA_VERSION = 1;
export const CONTEXT_STEADY_ACTIVATION_CUSTOM_TYPE = "san.context_steady.activation";

export interface ContextSteadyActivation {
	schemaVersion: typeof CONTEXT_STEADY_ACTIVATION_SCHEMA_VERSION;
	activationThresholdTokens: number;
	observedInputTokens: number;
}
export const TURN_DIGEST_SCHEMA_VERSION = 1;
export const TURN_DIGEST_CUSTOM_TYPE = "san.turn_digest";
export const CONTEXT_SEGMENT_SCHEMA_VERSION = 2;
export const CONTEXT_SEGMENT_CUSTOM_TYPE = "san.context_segment";
export const CONTEXT_CONTINUATION_SCHEMA_VERSION = 1;
export const CONTEXT_CONTINUATION_MESSAGE_TYPE = "san.context_continuation.authority";
export const CONTEXT_MAINTENANCE_SCHEMA_VERSION = 1;
export const CONTEXT_MAINTENANCE_CUSTOM_TYPE = "san.context_maintenance";
export const CONTEXT_CHECKPOINT_SCHEMA_VERSION = 2;
export const CONTEXT_CHECKPOINT_CUSTOM_TYPE = "san.context_checkpoint";
export const CONTEXT_PACKET_SCHEMA_VERSION = 1;
export const CONTEXT_PACKET_CUSTOM_TYPE = "san.context_packet";
export const CONTEXT_PACKET_MESSAGE_TYPE = "san.context_packet.injected";

/** Identifies the session span this digest covers. */
export interface TurnDigestSource {
	sessionId: string;
	/** First entry id in the digested span (inclusive). */
	fromEntryId: string;
	/** Last entry id in the digested span (inclusive). */
	toEntryId: string;
	/** Prompt generation counter at the time of digestion. */
	promptGeneration: number;
	/** The user message entry id that started this turn, if identifiable. */
	userEntryId?: string;
}

/** Evidence record for a single file touched this turn. */
export interface TurnDigestFile {
	path: string;
	action: "read" | "modified" | "created" | "deleted" | "unknown";
	reason?: string;
}

/** Evidence record for a single tool invocation. */
export interface TurnDigestToolEvidence {
	tool: string;
	summary: string;
	entryIds?: string[];
}

/** 摘要生成的候选记忆。 */
export interface TurnDigestMemoryCandidate {
	content: string;
	type: "preference" | "project_fact" | "decision" | "workflow" | "other";
	importance: number;
	/** 仅由本地权威用户消息分类器设置。 */
	authorization?: "explicit_user" | "inferred";
}

/** Optional token usage snapshot for the turn. */
export interface TurnDigestTokenStats {
	input?: number;
	output?: number;
	cacheRead?: number;
	cacheWrite?: number;
	total?: number;
}

export type TurnDigestFallbackReason =
	| "llm_disabled"
	| "model_unresolved"
	| "auth_unavailable"
	| "timeout"
	| "structured_output_invalid"
	| "request_failed";

/**
 * Structured digest of a settled agent turn.
 *
 * Stored as `data` on a CustomEntry with `customType = "san.turn_digest"`.
 * Does NOT participate in LLM context (CustomEntry contract).
 */
export interface TurnDigest {
	schemaVersion: typeof TURN_DIGEST_SCHEMA_VERSION;
	turnId: string;
	sessionId: string;
	createdAt: string;
	/** Model that produced the final assistant message for this turn. */
	model?: string;
	/** Source span in the session journal. */
	source: TurnDigestSource;
	/** One-sentence summary of what the user asked for. */
	userIntent: string;
	/** Concrete actions the agent took. */
	actionsTaken: string[];
	/** Key decisions the agent made. */
	decisions: string[];
	/** Files this turn touched. */
	filesTouched: TurnDigestFile[];
	/** Tool invocations with short summaries. */
	toolEvidence: TurnDigestToolEvidence[];
	/** Facts the agent learned during this turn. */
	factsLearned: string[];
	/** Questions that remain unanswered. */
	openQuestions: string[];
	/** Risks the agent identified. */
	risks: string[];
	/** Suggested next steps. */
	nextSteps: string[];
	/** Candidate memories (not auto-retained). */
	memoryCandidates: TurnDigestMemoryCandidate[];
	/** Token usage for the turn, if available. */
	tokenStats?: TurnDigestTokenStats;
	/** True when this digest was generated by the deterministic fallback path. */
	fallback: boolean;
	/** fallback 的明确原因；权威摘要不设置。 */
	fallbackReason?: TurnDigestFallbackReason;
	/** append-only 升级所替代的 fallback digest entry。 */
	supersedesEntryId?: string;
}

export type ContextMaintenanceTrigger =
	| "segment_tokens"
	| "segment_duration"
	| "steady_target"
	| "native_threshold"
	| "hard_pressure"
	| "overflow"
	| "incomplete"
	| "idle"
	| "manual"
	| "legacy_threshold";
/** @deprecated 请改用 ContextMaintenanceTrigger。 */
export type ContextSegmentMaintenanceReason = ContextMaintenanceTrigger;
export type ContextSegmentMaintenancePhase = "pre_turn" | "mid_turn" | "post_turn";
export type ContextSegmentAuthority = "checkpoint" | "context-full" | "snapcompact" | "remote" | "extension";
export type ContextMaintenanceAction =
	| "checkpoint"
	| "context-full"
	| "snapcompact"
	| "remote_compaction"
	| "handoff"
	| "none";

export type ContextMaintenanceFailureStage =
	| "preparation"
	| "extension_cancelled"
	| "model_unavailable"
	| "compaction_failed";

export interface ContextContinuationToolEvidence {
	tool: string;
	toolCallId: string;
	resultEntryId: string;
	path?: string;
	resource?: string;
	command?: string;
}

export type ContextSummarySource = "local" | "remote" | "snapcompact" | "extension" | "deterministic_fallback";

export interface ContextSummaryAuthorityAudit {
	summarySource: ContextSummarySource;
	forbiddenGoalField: boolean;
	executionClaimConflictCount: number;
	repairAttempted: boolean;
	repairSucceeded: boolean;
	fallbackReason?: string;
}

export type ContextContinuationAuthoritySource = "journal" | "persisted" | "handoff" | "authority_source_missing";

/**
 * 当前逻辑 turn 的权威继续执行状态。
 *
 * 该状态只能由当前 branch journal 的真实 user/tool entries 同步派生；
 * compaction summary、assistant 自述和工具输出正文都不能写入这些字段。
 */
export interface ActiveContinuationState {
	schemaVersion: typeof CONTEXT_CONTINUATION_SCHEMA_VERSION;
	sessionId: string;
	/** 旧 v1 记录没有该字段，读取时按 journal 处理。 */
	authoritySource?: ContextContinuationAuthoritySource;
	/** handoff 场景下，权威 user entry 所在的来源会话。 */
	sourceSessionId?: string;
	logicalTurnId: string;
	activeUserEntryId: string;
	activeUserRequest: string;
	activeUserRequestTruncated?: boolean;
	activeUserRequestOriginalChars?: number;
	supersededUserEntryIds: string[];
	promptGeneration: number;
	createdAt: string;
	/** 最近一次物理摘要的越权审计；不存在物理摘要时不设置。 */
	summaryAuthority?: ContextSummaryAuthorityAudit;
	executionEvidence: {
		successfulMutations: ContextContinuationToolEvidence[];
		successfulVerifications: ContextContinuationToolEvidence[];
		observedResources: ContextContinuationToolEvidence[];
		successfulToolResults: number;
		failedToolResults: number;
		unclassifiedShellOrEvalResults: number;
		omittedEvidenceRefs?: number;
	};
}

/**
 * 长逻辑 turn 内部的上下文维护边界。
 *
 * Segment 只描述已被 compaction summary 替代的 journal 区间，不携带执行配额，
 * 也不能作为停止 agent 的条件。原始条目仍保留在 append-only journal 中。
 */
export interface ContextSegment {
	schemaVersion: typeof CONTEXT_SEGMENT_SCHEMA_VERSION;
	segmentId: string;
	logicalTurnId: string;
	sessionId: string;
	createdAt: string;
	status: "closed";
	authority: ContextSegmentAuthority;
	source: {
		fromEntryId: string;
		toEntryId: string;
		/** 只有物理 compaction Segment 才存在。 */
		firstKeptEntryId?: string;
		promptGeneration: number;
	};
	maintenance: {
		maintenanceId: string;
		trigger: ContextMaintenanceTrigger;
		matchedTriggers: ContextMaintenanceTrigger[];
		action: ContextMaintenanceAction;
		phase: ContextSegmentMaintenancePhase;
		tokensBefore: number;
		tokensAfter?: number;
		segmentDeltaTokens?: number;
		segmentElapsedMs?: number;
	};
	/** 非权威历史摘要；checkpoint-only Segment 不设置。 */
	historicalSummary?: string;
	shortSummary?: string;
	/** 本地同步生成的最小继续执行状态；摘要模型失败时仍可用于恢复。 */
	checkpoint: Pick<
		TurnDigest,
		| "userIntent"
		| "actionsTaken"
		| "decisions"
		| "filesTouched"
		| "toolEvidence"
		| "factsLearned"
		| "openQuestions"
		| "risks"
		| "nextSteps"
		| "tokenStats"
	> & {
		/** 当前会话真实 user entry；压缩模型无权改写。 */
		activeUserEntryId: string;
	};
}

export interface ContextMaintenanceAudit {
	schemaVersion: typeof CONTEXT_MAINTENANCE_SCHEMA_VERSION;
	maintenanceId: string;
	sessionId: string;
	createdAt: string;
	promptGeneration: number;
	state: "maintenance" | "recovered" | "paused_for_context";
	reason: ContextMaintenanceTrigger;
	phase: ContextSegmentMaintenancePhase;
	recoveryAttempt: number;
	projectedInputTokens?: number;
	requiredTokens?: number;
	activeEntryCount?: number;
	archivedEntryCount?: number;
	detail?: string;
	failureStage?: ContextMaintenanceFailureStage;
}

/** Minimal context-steady settings (subset of full settings schema). */
export interface ContextSteadySettings {
	enabled: boolean;
	digest: {
		enabled: boolean;
		persistFallback: boolean;
		timeoutMs: number;
		llm?: {
			enabled: boolean;
			modelRole: string;
		};
	};
}

export interface ContextPacketSettings {
	enabled: boolean;
	recentDigests: number;
	maxTokens: number;
	qualityWindowTokens: number;
	reserveRatio: number;
}

export interface ContextRecallItem {
	id?: string;
	content: string;
	source?: string;
	timestamp?: string;
	score?: number;
	memoryType?: string;
	scope?: string;
}

export interface ContextPacketRecallLayer {
	query: string;
	items: ContextRecallItem[];
	tokenBudget: number;
	policyVersion?: string;
	selectedPolicyIds?: string[];
	queryTemplateId?: string;
	skipReasons?: Array<{ ownerId: string; reason: string }>;
}

export interface ContextCheckpointSummaryItem {
	text: string;
	entryRefs: string[];
}

export type ContextCheckpointRebaseReason = "checkpoint" | "resume" | "budget_pressure" | "topic_shift";

export interface ContextCheckpoint {
	schemaVersion: typeof CONTEXT_CHECKPOINT_SCHEMA_VERSION;
	checkpointId: string;
	sessionId: string;
	/** v2 epoch id for bounded ContextPlan rebases. Absent on legacy v1 checkpoints. */
	epochId?: string;
	createdAt: string;
	entryRefs: string[];
	/** v2 raw source refs covered by the checkpoint. Absent on legacy v1 checkpoints. */
	coveredSourceEntryRefs?: string[];
	/** v2 prior checkpoint custom-entry ref when this checkpoint extends one. */
	previousCheckpointEntryId?: string;
	/** v2 reason this checkpoint can act as a safe rebase boundary. */
	rebaseReason?: ContextCheckpointRebaseReason;
	fromDigestEntryId: string;
	toDigestEntryId: string;
	digestCount: number;
	summary: {
		userIntents: ContextCheckpointSummaryItem[];
		decisions: ContextCheckpointSummaryItem[];
		filesTouched: Array<ContextCheckpointSummaryItem & { action: TurnDigestFile["action"] }>;
		risks: ContextCheckpointSummaryItem[];
		nextSteps: ContextCheckpointSummaryItem[];
	};
	tokenEstimate: number;
	tokenBudget: number;
	stability: "stable";
	cachePriority: "high";
}

export interface ContextPacketLayer {
	name: "stable_checkpoint" | "turn_digest_ledger" | "retrieved_context";
	entryRefs: string[];
	tokenEstimate: number;
	tokenBudget: number;
	trimmed: number;
	stability: "stable" | "append-only" | "volatile";
	cachePriority: "high" | "medium" | "low";
}

export interface ContextPacketTrimDecision {
	layer: ContextPacketLayer["name"];
	reason: "recent_limit" | "token_budget" | "checkpoint_covered" | "topic_shift" | "packet_total_budget";
	omitted: number;
}

export interface ContextPacket {
	schemaVersion: typeof CONTEXT_PACKET_SCHEMA_VERSION;
	packetId: string;
	sessionId: string;
	createdAt: string;
	currentPromptPreview: string;
	layers: ContextPacketLayer[];
	checkpointRef?: string;
	digestRefs: string[];
	recallQuery?: string;
	recallRefs: string[];
	recallPolicy?: {
		policyVersion: string;
		selectedPolicyIds: string[];
		queryTemplateId?: string;
		skipReasons: Array<{ ownerId: string; reason: string }>;
	};
	tokenEstimate: number;
	tokenBudget: number;
	budget: {
		qualityWindowTokens: number;
		reserveRatio: number;
		reservedTokens: number;
		packetTokenBudget: number;
		configuredPacketMaxTokens: number;
	};
	trimDecisions: ContextPacketTrimDecision[];
	injectedMessageCustomType: typeof CONTEXT_PACKET_MESSAGE_TYPE;
	injectedMessageId?: string;
}
