/**
 * Context Steady State M1 — TurnDigest types.
 *
 * M1 only: post-turn TurnDigest generation + persistence.
 * No ContextPacket injection, no LLM context mutation, no mnemopi recall/retain.
 */

export const TURN_DIGEST_SCHEMA_VERSION = 1;
export const TURN_DIGEST_CUSTOM_TYPE = "san.turn_digest";

/** Identifies the session span this digest covers. */
export interface TurnDigestSource {
	sessionId: string;
	/** First entry id in the digested span (inclusive). */
	fromEntryId: string;
	/** Last entry id in the digested span (inclusive). */
	toEntryId: string;
	/** Prompt generation counter at the time of digestion. */
	promptGeneration: number;
	/** The user message entry id that started this turn, if identifiable. */
	userEntryId?: string;
}

/** Evidence record for a single file touched this turn. */
export interface TurnDigestFile {
	path: string;
	action: "read" | "modified" | "created" | "deleted" | "unknown";
	reason?: string;
}

/** Evidence record for a single tool invocation. */
export interface TurnDigestToolEvidence {
	tool: string;
	summary: string;
	entryIds?: string[];
}

/** Candidate memory item — produced by digest, consumed by M4+. */
export interface TurnDigestMemoryCandidate {
	content: string;
	type: "preference" | "project_fact" | "decision" | "workflow" | "other";
	importance: number;
}

/** Optional token usage snapshot for the turn. */
export interface TurnDigestTokenStats {
	input?: number;
	output?: number;
	cacheRead?: number;
	cacheWrite?: number;
	total?: number;
}

/**
 * Structured digest of a settled agent turn.
 *
 * Stored as `data` on a CustomEntry with `customType = "san.turn_digest"`.
 * Does NOT participate in LLM context (CustomEntry contract).
 */
export interface TurnDigest {
	schemaVersion: typeof TURN_DIGEST_SCHEMA_VERSION;
	turnId: string;
	sessionId: string;
	createdAt: string;
	/** Model that produced the final assistant message for this turn. */
	model?: string;
	/** Source span in the session journal. */
	source: TurnDigestSource;
	/** One-sentence summary of what the user asked for. */
	userIntent: string;
	/** Concrete actions the agent took. */
	actionsTaken: string[];
	/** Key decisions the agent made. */
	decisions: string[];
	/** Files this turn touched. */
	filesTouched: TurnDigestFile[];
	/** Tool invocations with short summaries. */
	toolEvidence: TurnDigestToolEvidence[];
	/** Facts the agent learned during this turn. */
	factsLearned: string[];
	/** Questions that remain unanswered. */
	openQuestions: string[];
	/** Risks the agent identified. */
	risks: string[];
	/** Suggested next steps. */
	nextSteps: string[];
	/** Candidate memories (not auto-retained). */
	memoryCandidates: TurnDigestMemoryCandidate[];
	/** Token usage for the turn, if available. */
	tokenStats?: TurnDigestTokenStats;
	/** True when this digest was generated by the deterministic fallback path. */
	fallback: boolean;
}

/** Minimal context-steady settings (subset of full settings schema). */
export interface ContextSteadySettings {
	enabled: boolean;
	digest: {
		enabled: boolean;
		persistFallback: boolean;
		timeoutMs: number;
	};
}
