/**
 * Context Steady State types.
 */

export const TURN_DIGEST_SCHEMA_VERSION = 1;
export const TURN_DIGEST_CUSTOM_TYPE = "san.turn_digest";
export const CONTEXT_CHECKPOINT_SCHEMA_VERSION = 1;
export const CONTEXT_CHECKPOINT_CUSTOM_TYPE = "san.context_checkpoint";
export const CONTEXT_PACKET_SCHEMA_VERSION = 1;
export const CONTEXT_PACKET_CUSTOM_TYPE = "san.context_packet";
export const CONTEXT_PACKET_MESSAGE_TYPE = "san.context_packet.injected";

/** Identifies the session span this digest covers. */
export interface TurnDigestSource {
	sessionId: string;
	/** First entry id in the digested span (inclusive). */
	fromEntryId: string;
	/** Last entry id in the digested span (inclusive). */
	toEntryId: string;
	/** Prompt generation counter at the time of digestion. */
	promptGeneration: number;
	/** The user message entry id that started this turn, if identifiable. */
	userEntryId?: string;
}

/** Evidence record for a single file touched this turn. */
export interface TurnDigestFile {
	path: string;
	action: "read" | "modified" | "created" | "deleted" | "unknown";
	reason?: string;
}

/** Evidence record for a single tool invocation. */
export interface TurnDigestToolEvidence {
	tool: string;
	summary: string;
	entryIds?: string[];
}

/** Candidate memory item — produced by digest, consumed by M4+. */
export interface TurnDigestMemoryCandidate {
	content: string;
	type: "preference" | "project_fact" | "decision" | "workflow" | "other";
	importance: number;
}

/** Optional token usage snapshot for the turn. */
export interface TurnDigestTokenStats {
	input?: number;
	output?: number;
	cacheRead?: number;
	cacheWrite?: number;
	total?: number;
}

/**
 * Structured digest of a settled agent turn.
 *
 * Stored as `data` on a CustomEntry with `customType = "san.turn_digest"`.
 * Does NOT participate in LLM context (CustomEntry contract).
 */
export interface TurnDigest {
	schemaVersion: typeof TURN_DIGEST_SCHEMA_VERSION;
	turnId: string;
	sessionId: string;
	createdAt: string;
	/** Model that produced the final assistant message for this turn. */
	model?: string;
	/** Source span in the session journal. */
	source: TurnDigestSource;
	/** One-sentence summary of what the user asked for. */
	userIntent: string;
	/** Concrete actions the agent took. */
	actionsTaken: string[];
	/** Key decisions the agent made. */
	decisions: string[];
	/** Files this turn touched. */
	filesTouched: TurnDigestFile[];
	/** Tool invocations with short summaries. */
	toolEvidence: TurnDigestToolEvidence[];
	/** Facts the agent learned during this turn. */
	factsLearned: string[];
	/** Questions that remain unanswered. */
	openQuestions: string[];
	/** Risks the agent identified. */
	risks: string[];
	/** Suggested next steps. */
	nextSteps: string[];
	/** Candidate memories (not auto-retained). */
	memoryCandidates: TurnDigestMemoryCandidate[];
	/** Token usage for the turn, if available. */
	tokenStats?: TurnDigestTokenStats;
	/** True when this digest was generated by the deterministic fallback path. */
	fallback: boolean;
}

/** Minimal context-steady settings (subset of full settings schema). */
export interface ContextSteadySettings {
	enabled: boolean;
	digest: {
		enabled: boolean;
		persistFallback: boolean;
		timeoutMs: number;
	};
}

export interface ContextPacketSettings {
	enabled: boolean;
	recentDigests: number;
	maxTokens: number;
	qualityWindowTokens: number;
	reserveRatio: number;
}

export interface ContextCheckpointSummaryItem {
	text: string;
	entryRefs: string[];
}

export interface ContextCheckpoint {
	schemaVersion: typeof CONTEXT_CHECKPOINT_SCHEMA_VERSION;
	checkpointId: string;
	sessionId: string;
	createdAt: string;
	entryRefs: string[];
	fromDigestEntryId: string;
	toDigestEntryId: string;
	digestCount: number;
	summary: {
		userIntents: ContextCheckpointSummaryItem[];
		decisions: ContextCheckpointSummaryItem[];
		filesTouched: Array<ContextCheckpointSummaryItem & { action: TurnDigestFile["action"] }>;
		risks: ContextCheckpointSummaryItem[];
		nextSteps: ContextCheckpointSummaryItem[];
	};
	tokenEstimate: number;
	tokenBudget: number;
	stability: "stable";
	cachePriority: "high";
}

export interface ContextPacketLayer {
	name: "stable_checkpoint" | "turn_digest_ledger";
	entryRefs: string[];
	tokenEstimate: number;
	tokenBudget: number;
	trimmed: number;
	stability: "stable" | "append-only";
	cachePriority: "high" | "medium";
}

export interface ContextPacketTrimDecision {
	layer: ContextPacketLayer["name"];
	reason: "recent_limit" | "token_budget" | "checkpoint_covered";
	omitted: number;
}

export interface ContextPacket {
	schemaVersion: typeof CONTEXT_PACKET_SCHEMA_VERSION;
	packetId: string;
	sessionId: string;
	createdAt: string;
	currentPromptPreview: string;
	layers: ContextPacketLayer[];
	checkpointRef?: string;
	digestRefs: string[];
	tokenEstimate: number;
	tokenBudget: number;
	budget: {
		qualityWindowTokens: number;
		reserveRatio: number;
		reservedTokens: number;
		packetTokenBudget: number;
		configuredPacketMaxTokens: number;
	};
	trimDecisions: ContextPacketTrimDecision[];
	injectedMessageCustomType: typeof CONTEXT_PACKET_MESSAGE_TYPE;
	injectedMessageId?: string;
}
